title: "Rui Khembo"
email: rui.khembo@gmail.com
description: "Produtor de Vídeos & Fotos"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

paginate: 12
paginate_path: /page:num/
permalink: pretty

plugins:
    - jekyll-seo-tag
    - jekyll-menus
    - jekyll-paginate
    - jekyll-sitemap

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/images/logo.svg
logo:

exclude:
    - bower_components

# Author
author: Ivo Zinenda
author_email: info@izitag.site

# Collections
collections:
    rui_khembo: